export const EXISTING_ASSETS = [
  {
    id: "k-gov-skill",
    name: "k-gov-skill",
    url: "https://github.com/hosungseo/k-gov-skill",
    category: "Skill hub",
    auth: "mixed",
    pitch: "공무원이 Claude Code, Codex, OpenClaw에서 바로 쓸 수 있는 행정업무 AI 스킬 모음집.",
    agentUse: "법령, 공공데이터포털, 관보, 국회자료, HWP 문서, 직제·정원 검토를 skill README와 recipe로 발견하고 실행.",
    hook: "공공 API·관보·HWP 같은 귀찮은 실무 병목을 에이전트가 다루게 만든다.",
  },
  {
    id: "korean-government-api-bundle",
    name: "korean-government-api-bundle",
    url: "https://github.com/hosungseo/korean-government-api-bundle",
    category: "API bundle",
    auth: "user-key-required",
    pitch: "공공데이터포털·국회·경제통계 등 한국 정부 API를 에이전트가 호출하기 쉽게 묶는 핵심 도구 번들.",
    agentUse: "API 후보 탐색, serviceKey 필요 여부 확인, 호출 파라미터 생성, 결과를 업무 패킷 근거자료로 저장.",
    hook: "공공 API 문서를 뒤지는 시간을 줄인다.",
  },
  {
    id: "ai-readable-government",
    name: "ai-readable-government",
    url: "https://github.com/hosungseo/ai-readable-government",
    category: "Reader",
    auth: "none",
    pitch: "보도자료와 관보를 에이전트와 사람이 함께 읽는 공공문서 reader.",
    agentUse: "공식 문서 원문, 날짜, 기관, readable layer를 보존하며 요약·비교·브리핑 생성.",
    hook: "어제 정부가 무엇을 냈는지 바로 읽힌다.",
  },
  {
    id: "gov-press-md",
    name: "gov-press-md",
    url: "https://github.com/hosungseo/gov-press-md",
    category: "Data commons",
    auth: "none",
    pitch: "정책브리핑 보도자료를 날짜·부처별 Markdown DB로 정리한 원천 코퍼스.",
    agentUse: "부처별 보도자료 검색, 정책 변화 추적, 출처 기반 브리핑 작성.",
    hook: "정부 보도자료를 에이전트가 바로 grep하고 요약한다.",
  },
  {
    id: "ai-readable-gazette-kr",
    name: "ai-readable-gazette-kr",
    url: "https://github.com/hosungseo/ai-readable-gazette-kr",
    category: "Data commons",
    auth: "none",
    pitch: "대한민국 관보 12.8만건을 Markdown으로 제공하는 공개 코퍼스.",
    agentUse: "고시·공고·직제·입법예고를 문서 DB처럼 검색하고 근거 링크로 연결.",
    hook: "관보 PDF를 뒤지는 고통을 줄인다.",
  },
  {
    id: "agent-ready-check",
    name: "agent-ready-check",
    url: "https://github.com/hosungseo/agent-ready-check",
    category: "Scanner",
    auth: "none",
    pitch: "공공 웹사이트의 llms.txt, MCP, OpenAPI, robots, metadata 준비도를 점검하는 스캐너.",
    agentUse: "기관 사이트가 에이전트에게 얼마나 읽히는지 점수화하고 개선 과제를 제안.",
    hook: "우리 기관 사이트가 AI에게 읽히는지 바로 점검한다.",
  },
  {
    id: "newcomer-onboarding-wiki",
    name: "newcomer-onboarding-wiki",
    url: "https://github.com/hosungseo/newcomer-onboarding-wiki",
    category: "Knowledge wiki",
    auth: "none",
    pitch: "신규공무원·인사이동자를 위한 행정문서·업무 적응 지식 위키.",
    agentUse: "공문, 전자서명, 조직 연결축, FAQ를 에이전트가 찾아 신규 담당자에게 설명.",
    hook: "처음 맡은 업무의 암묵지를 검색 가능하게 만든다.",
  },
  {
    id: "public-data-portal-intelligence",
    name: "public-data-portal-intelligence",
    url: "https://github.com/hosungseo/public-data-portal-intelligence",
    category: "Review queue",
    auth: "none",
    pitch: "공공데이터포털 파일데이터를 API 전환 후보로 검토하는 우선순위 큐.",
    agentUse: "파일데이터를 API화할 때의 전환 가능성, 제공기관 alias, usage fit을 검토하는 샘플로 사용.",
    hook: "공공데이터를 그냥 올리는 단계에서 에이전트가 쓰기 쉬운 API로 바꾸는 단계로 넘어간다.",
  },
  {
    id: "gonpunclaw-web",
    name: "gonpunclaw-web",
    url: "https://github.com/hosungseo/gonpunclaw-web",
    category: "Use-case hub",
    auth: "none",
    pitch: "공무원·공공기관 AI 업무자동화 100선 콘텐츠 허브.",
    agentUse: "업무자동화 아이디어를 과업·부처·도구 후보로 재분류해 skill recipe의 출발점으로 사용.",
    hook: "내 업무도 자동화할 수 있는지 사례로 먼저 설득한다.",
  },
  {
    id: "gonpunclaw-policymap",
    name: "gonpunclaw-policymap",
    url: "https://github.com/hosungseo/gonpunclaw-policymap",
    category: "Self-service app",
    auth: "optional-user-key",
    pitch: "주소 엑셀을 올리면 공개 정책지도가 되는 중앙부처 사무관용 셀프서비스 도구.",
    agentUse: "엑셀 컬럼 점검, 주소 정규화, 지도 공개 전 검토 패킷과 운영 로그 작성에 연결.",
    hook: "엑셀을 지도로 바꾸는 눈에 보이는 효용이 있다.",
  },
  {
    id: "news-policy-linker",
    name: "news-policy-linker",
    url: "https://github.com/hosungseo/news-policy-linker",
    category: "Policy linker",
    auth: "none",
    pitch: "뉴스를 공식 정책, 통계, 지원제도로 이어주는 reader skeleton.",
    agentUse: "기사 기반 질문을 정책자료·숫자·지원제도 후보로 연결하는 레시피 샘플.",
    hook: "뉴스를 읽고 끝내지 않고 바로 정책 근거로 이어준다.",
  },
  {
    id: "minganwitak-inspector",
    name: "minganwitak-inspector",
    url: "https://github.com/hosungseo/minganwitak-inspector",
    category: "Inspection app",
    auth: "none",
    pitch: "국가사무 민간위탁 실태점검 시스템 데모.",
    agentUse: "점검표, 증빙자료, 보완요구, reviewer queue를 행정업무 패킷 예시로 제공.",
    hook: "검토와 점검 업무를 review queue로 바꾸는 예시가 된다.",
  },
];
